window.config = {
	extension_sources: {
		GitHub: 'https://raw.githubusercontent.com/libccy/noname-extension/diy/',
	},
	extension_source: 'Coding',
	forbidai: ['ns_liuzhang'],
	forbidai_user: [],
	forbidall: [],
	forbidstone: ['zhugedan', 'hs_malfurion', 'lusu', 'chenlin', 'hs_siwangzhiyi',
		'yuanshao', 're_daqiao', 'hs_xuanzhuanjijia',
		'zhuran', 'huatuo', 'hs_guldan', 'wangyi', 'caoang',
		'guojia', 're_guojia', 'shen_caocao', 'caopi', 'hs_yngvar', 'guansuo',
		'hs_anduin', 'hs_antonidas', 'xushi', 'hs_lreno'
	],
	forbidchess: ['hetaihou'],
	forbidboss: ['caiwenji'],
	forbiddouble: ['zhugedan', 'dongzhuo', 'wutugu', 'hs_siwangzhiyi', 'hs_ronghejuren', 'hs_shanlingjuren'],
	forbidthreecard: ['qiankunbiao', 'shenhuofeiya'],
	zhinang_tricks: ['guohe', 'wuxie', 'wuzhong', 'dongzhuxianji'],
	connect_zhinang_tricks: ['guohe', 'wuxie', 'wuzhong', 'dongzhuxianji'],
	all: {
		sgscharacters: ['standard', 'shenhua', 'xinghuoliaoyuan', 'refresh', 'yijiang', 'sp', 'sp2', 'xianding', 'huicui', 'extra', 'old', 'mobile', 'shiji', 'tw', 'yingbian', 'offline', 'jsrg', 'sb', 'clan', 'collab'],
		sgscards: ['standard', 'extra', 'sp', 'guozhan', 'zhulu', 'yingbian', 'yongjian'],
		sgsmodes: ['identity', 'guozhan', 'versus', 'doudizhu', 'single', 'brawl', 'connect'],
		stockmode: ['identity', 'guozhan', 'versus', 'boss', 'doudizhu', 'single', 'chess', 'stone', 'connect', 'brawl', 'tafang'],
		stockextension: ['boss', 'cardpile', 'coin', 'wuxing'],
		layout: ['default', 'newlayout'],
		theme: ['woodden', 'music', 'simple'],
		card_font: ['xiaozhuan', 'huangcao', 'caoshu', 'xingshu'],
		double_hp: ['hejiansan', 'pingjun', 'zuidazhi', 'zuixiaozhi', 'zonghe'],
		image_background_filter: ['default', 'blur', 'gray', 'sepia', 'invert', 'saturate', 'contrast', 'hue', 'brightness'],
	},

	game: 'sgs',
	duration: 500,
	hoveration: 1000,
	doubleclick_intro: true,
	cheat: false,
	volumn_background: 3,
	volumn_audio: 8,

	connect_avatar: 'caocao',
	connect_nickname: '无名玩家',
	config_menu: true,
	auto_popped_config: true,
	auto_popped_history: true,
	auto_skill: true,
	auto_confirm: true,
	enable_drag: false,
	enable_pressure: false,
	pressure_taptic: true,
	hover_handcard: true,
	hover_all: true,
	right_info: true,
	longpress_info: true,
	long_info: true,
	background_music: 'music_default',
	background_audio: true,
	background_speak: true,
	glow_phase: 'yellow',
	die_move: 'flip',


	low_performance: true,
	compatiblemode: true,
	confirm_exit: true,
	skip_shan: true,
	unauto_choose: true,
	touchscreen: true,
	swipe_left: 'pause',
	swipe_right: 'pause',
	dev: true,
	errstop: true,
	player_height: 'short',
	phonelayout: true,
	player_style: 'simple',
	fold_mode: false,
	cardtempname: 'horizon',
	name_font: 'shousha',
	identity_font: 'shousha',
	cardtext_font: 'yuanli',
	global_font: 'yuanli',
	show_time: true,
	show_time2: true,
	remember_round_button: true,
	remember_dialog: true,
	character_dialog_tool: 'all',
	show_favourite: true,
	show_cardpile_number: true,
	wuxie_right: false,
	show_discardpile: true,
	ui_zoom: 'normal',
	revive: true,
	continue_game: true,
	show_replay: true,
	show_rarity: true,

	skin: {},
	gameRecord: {},
	extensionInfo: {},
	autoskilllist: [],
	hiddenModePack: [],
	hiddenCharacterPack: [],
	hiddenCardPack: [],
	hiddenPlayPack: [],
	hiddenBackgroundPack: [],
	customBackgroundPack: [],
	favouriteCharacter: [],
	favouriteMode: [],
	recentIP: [],
	vintageSkills: [],
	alteredSkills: [],
	brokenFile: [],

	theme: 'simple',
	layout: 'nova',
	card_style: 'ol',
	cardback_style: 'ol',
	hp_style: 'glass',

	image_character: 'default',
	image_background: 'default',

	asset_image: true,
	asset_font: true,

	card_font: 'xiaozhuan',
	show_statusbar_ios: 'off',
	show_statusbar_android: true,
	show_name: true,
	show_replay: false,
	show_round_menu: true,
	show_pause: true,
	show_auto: true,
	show_volumn: true,
	show_cardpile: true,
	only_fullskin: true,
	show_connect: true,
	show_wuxie: false,
	show_wuxie_self: true,
	show_stat: true,
	show_playerids: true,
	show_scrollbar: false,
	mousewheel: true,
	fold_card: true,
	threed_card: false,
	vertical_scroll: false,
	handcard_scroll: 0,
	animation: false,
	skill_animation_type: 'default',
	paused: false,
	title: false,
	button_press: true,
	damage_shake: false,
	log_highlight: true,
	player_border: 'normal',
	radius_size: 'default',

	modeconfig: false,
	gameconfig: false,
	appearence: false,
	video: '0',
	coin: 0,

	intro: 'i',
	right_click: 'pause',
	sort: 'type_sort',

	cards: ['standard', 'extra'],
	characters: ['shenhua', 'sp', 'yijiang', 'refresh', 'xinghuoliaoyuan', 'extra', 'collab', 'happy'],
	connect_characters: ['diy'],
	connect_cards: ['huanlekapai', 'guozhan', 'sp', 'zhulu', 'yingbian', 'yongjian'],
	plays: [],
	// extensions: ['十周年UI', '祖安武将', '欢乐三国杀'],
	extensions: ['祖安武将', '欢乐三国杀'],
	banned: [],
	bannedcards: [],
	forbidlist: [],
	bannedpile: {},
	customcardpile: {},
	addedpile: {},

	mode: 'identity',
	mode_config: {
		global: {
			player_number: 8,
			auto_identity: 'off',
			double_character: false,
			save_progress: true,
			free_choose: true,
			swap: true,
			change_identity: true,
			battle_number: 3,
			double_hp: 'pingjun',
		},
		identity: {
			identity: [
				['zhu', 'fan'],
				['zhu', 'nei', 'fan'],
				['zhu', 'zhong', 'nei', 'fan'],
				['zhu', 'zhong', 'nei', 'fan', 'fan'],
				['zhu', 'zhong', 'nei', 'fan', 'fan', 'fan'],
				['zhu', 'zhong', 'zhong', 'nei', 'fan', 'fan', 'fan'],
				['zhu', 'zhong', 'zhong', 'nei', 'fan', 'fan', 'fan', 'fan'],
			],
			choice: {
				zhu: 3,
				zhong: 4,
				nei: 5,
				fan: 3,
			},
			choice_zhu: '4',
			choice_zhong: '5',
			choice_fan: '4',
			choice_nei: '6',
			show_identity: true,
			difficulty: 'normal',
			dierestart: true
		},
		guozhan: {
			difficulty: 'normal',
			initshow_draw: 'mark',
			dierestart: true
		},
	},
	current_mode: {},
	customforbid: [],
	forbid: [
		['huashen'],
		['rehuashen'],
		['xinmanjuan'],
		//['xinleiji','fuji'],
		['xinleiji', 'xinfu_jijun'],
		['reluanji', 'jueqing'],
		['lianying', 'rende'],
		['lianying', 'anxian'],
		['lianying', 'yinguo'],
		['lianying', 'qingjian'],
		['boss_juejing', 'rende'],
		['boss_juejing', 'anxian'],
		['boss_juejing', 'yinguo'],
		['boss_juejing', 'qingjian'],
		['shangshi', 'rende'],
		['shangshi', 'anxian'],
		['shangshi', 'yinguo'],
		['shangshi', 'qingjian'],
		['rende', 'relianying'],
		['anxian', 'relianying'],
		['yinguo', 'relianying'],
		['shenxing', 'relianying'],
		['qingjian', 'relianying'],
		['rende', 'yuling'],
		['anxian', 'yuling'],
		['yinguo', 'yuling'],
		['qingjian', 'yuling'],
		//['qingnang','yiji'],
		//['qingnang','reyiji'],
		//['qingjian','tuntian'],
		// ['yiji','tuntian'],
		// ['reyiji','tuntian'],
		['tuntian', 'guidao'],
		['tuntian', 'tiandao'],
		['tuntian', 'huanshi'],
		// ['tuntian','guicai'],
		// ['jiang','chongzhen'],
		// ['fenji','yuling'],
		['jiushi', 'guixin'],
		['xiuhua', 'qiaoxie'],
		['xiuhua', 'xuanfeng'],
		['xiuhua', 'duanxing'],
		['xiuhua', 'xiaoji'],
		['xiuhua', 'xiaoji'],
		// ['jiushi','jushou'],
		// ['jiushi','kuiwei'],
		['zishu', 'xinfu_songsang'],
		['zishu', 'shenxing'],
		['minishendao', 'luoshen'],
		['minishendao', 'reluoshen'],
		['akane_quanqing', 'lianying'],
		['akane_quanqing', 'relianying'],
		['akane_quanqing', 'shangshi'],
		['dcruyi', 'cxliushi'],
	]
};
