window.noname_update = {
	version: '1.10.4',
	update: '1.10.3.1',
	changeLog: [
		'整合@copcap @PZ157 @mengxinzxz @lieren2023 @CatIgnore @Tipx-L @kuangshen04 @nonameShijian @universe-st @BauxiteAl @Rintim @S-N-O-R-L-A-X @xiaoas @kola-king @Howard-Zhou-77 的Pull Request',
		'《江山如故·转》武将包；神贾诩、族王沦、族荀攸、张曼成、星曹仁、吕伯奢、张燕、OL丁尚浣、OL李婉、数学孟优',
		'9人局+10人局、“谋攻篇”游戏模式、“群雄割据”模式常驻',
		'游戏内对象class化，事件handler等新机制',
		'其他AI优化与bug修复',
	],
	files: [
		'card/extra.js',
		'card/sp.js',
		'card/standard.js',
		'card/yingbian.js',
		'character/clan.js',
		'character/collab.js',
		'character/diy.js',
		'character/extra.js',
		'character/mobile.js',
		'character/huicui.js',
		'character/jsrg.js',
		'character/mobile.js',
		'character/offline.js',
		'character/old.js',
		'character/rank.js',
		'character/refresh.js',
		'character/sb.js',
		'character/shenhua.js',
		'character/shiji.js',
		'character/sp.js',
		'character/sp2.js',
		'character/standard.js',
		'character/tw.js',
		'character/xiake.js',
		'character/xianding.js',
		'character/xinghuoliaoyuan.js',
		'character/yijiang.js',
		'game/config.js',
		'game/game.js',
		'game/pinyinjs.js',
		'layout/default/layout.css',
		'layout/newlayout/global.css',
		'mode/connect.js',
		'mode/doudizhu.js',
		'mode/guozhan.js',
		'mode/identity.js',
		// 'mode/single.js',
		'mode/versus.js',
	]
};
