export default {
	// g绿 b蓝 r红 p粉
	hok_ailin: '#b捞德一评级:3.6',
	hok_anqila: '#b捞德一评级:3.9',
	hok_aoyin: '#r捞德一评级:4.0',
	hok_bailishouyue: '#b捞德一评级:3.7',
	hok_bailixuance: '#b捞德一评级:3.9',
	hok_daji: '#b捞德一评级:3.6',
	hok_dasiming: '#b捞德一评级:3.7',
	hok_donghuangtaiyi: '#b捞德一评级:3.7',
	hok_duoliya: '#b捞德一评级:3.9',
	hok_gaojianli: '#b捞德一评级:3.7',
	hok_hainuo: '#b捞德一评级:3.9',
	hok_houyi: '#b捞德一评级:3.9',
	hok_lan: '#b捞德一评级:3.7',
	hok_lanlingwang: '#b捞德一评级:3.7',
	hok_lixin: '#b捞德一评级:3.8',
	hok_makeboluo: '#b捞德一评级:3.7',
	hok_mingshiyin: '#b捞德一评级:3.8',
	hok_miyue: '#b捞德一评级:3.7',
	hok_mozi: '#b捞德一评级:3.7',
	hok_sikongzhen: '#b捞德一评级:3.8',
	hok_sunwukong: '#r捞德一评级:4.0',
	hok_wangzhaojun: '#b捞德一评级:3.8',
	hok_wuzetian: '#b捞德一评级:3.8',
	hok_yao: '#b捞德一评级:3.8',
	hok_yase: '#b捞德一评级:3.8',
	hok_sp_lixin: '#r捞德一评级:4.0',
	hok_sp_mingshiyin: '#r耀世圣手评级:4.0',
};
